config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/home', status: 302)
  get 'home', to: 'g_rabit#home', as: 'home'
  get 'messages', to: 'messages#messages', as: 'messages'
  get 'messages/:id', to: 'messages#message_board', as: 'message_board'
  post 'messages/:id', to: 'messages#send_message'
  devise_for :users
  get 'user_profile',to: 'g_rabit#user_profile', as: 'user_profile'
  get 'users', to: 'g_rabit#index', as: 'users' #list all users
  get 'users/:id',to:'g_rabit#deactivate', as:'deactivate' #Deactivated

  

  #routes for item model
  get 'items', to:'items#index', as:'items' #index
  get 'items/new', to: 'items#new', as: 'new_item' # new
  post 'items', to: 'items#create' # create
  get 'items/:id/edit', to: 'items#edit', as: 'edit_item' # edit
  patch 'items/:id', to: 'items#update' # update (as needed)
  put 'items/:id', to: 'items#update' # update (full replacement)
  get 'items/:id', to:'items#show', as:'item' #show
  delete 'items/:id', to: 'items#destroy' # destroy
  post 'items/:id',to:'items#reported' #reported

  get 'items/search_results/:id', to: 'items#search', as: 'search'
  get 'items/category_results/:id', to: 'items#search_by_category', as: 'category'

  #routes for Admin
  get 'administrator', to:'administrator#index', as:'admin' #index
  get 'reports', to:'administrator#view', as:'reports' #view
  get 'deactivated_users', to: 'administrator#userindex', as: 'deactivated_users' #list all deactivated users
  get 'deactivated_users/:id', to: 'administrator#reactivate', as: 'reactivate_users' #reactivate users
  get 'administrator/:id', to:'administrator#show', as:'admin_item' #show
  delete 'administrator/:id', to: 'administrator#destroy' # destroy
  
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :bigint           not null, primary key
#  content    :string
#  is_new     :boolean
#  recipient  :string
#  sender     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_messages_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Message < ApplicationRecord
    validates :sender, presence: true
    validates :recipient, presence: true
    belongs_to :user

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    #Note, this page will require the user to be signed in.SS
    def messages()
        respond_to do |format|
            format.html do
                if(user_signed_in?)
                signed_in_user = User.find_by_name(current_user.name)
                render :messages, locals: {signed_in_user: signed_in_user}
                
                else
                    flash[:error] = "You must be signed in to access messages."
                    redirect_to "/users/sign_in"
                end
             end

        end
    end

    def message_board()
        signed_in_user = User.find_by_name(current_user.name)
        all_messg = signed_in_user.messages
        messages = []
        all_messg.each do |m|
            if( (m.sender == params[:id] && m.recipient == signed_in_user.user_name) || (m.recipient == params[:id] && m.sender == signed_in_user.user_name))
                m.is_new = false;
                m.save!
                messages.push(m)
            end
        end
    
       
        respond_to do |format| 
            message_sender = User.find_by_user_name(params[:id])
            format.html{ render :message_board, locals: {message_sender: message_sender, messages: messages}}
        end
    end

    def send_message()
        message = Message.new(params.require(:message).permit(:content, :sender, :recipient))
        message.is_new = true;
        message.user_id = User.find_by_user_name(params[:id]).id
        message.save!

        message = Message.new(params.require(:message).permit(:content, :sender, :recipient))
        message.is_new = false
        message.user_id = current_user.id
        message.save!

        signed_in_user = User.find_by_name(current_user.name)

        respond_to do |format|
            format.html do
                redirect_back(fallback_location: root_path)
            end
        end
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/message_board.html.erb
<div style="margin-top:20px; background-color:lightgreen">
<center>
<i><h2 style="color:black"><b>Conversation with <%= message_sender.name %> </b></h2></i>
</center>
</div>


<center>

    <div id= "messagebox" class=scrollable>
        <p style="color:lightblue">
            <% messages.each do |m| %>
                <%= "[" + m.sender + "]: " +  m.content %><br/>
             
                      
            <% end %>

        </p>
    </div>


<div class = "footer">
    <%= form_with model: @message, url: message_board_path, method: :post, local: true, scope: :message do |m| %>
        <%= m.hidden_field :sender, :value => current_user.user_name %>
        <%= m.hidden_field :recipient, :value => params[:id] %>
       
       
        <div> <%= m.text_field :content, :size => "100%" %>  <%= m.submit "send", class: "btn btn-success" %> </div> 
    <% end %>

</div>
</center>

app/views/messages/messages.html.erb
<div style="margin-top:20px; margin-bottom:20px; background-color:lightgreen">
<center>
<i><h2 style="color:black"><b><%= signed_in_user.name%>'s Messages </b></h2></i>
</center>
</div>

<script>

  function setMessageThumbnailNotification(senders,messages)
  {
      for(let i = 0; i < senders.length; i++)
      {
        for(let j = 0; j < messages.length; j++)
        {
          if(senders[i]==messages[j].sender && messages[j].is_new)
            {
              var elementToChange = document.getElementById(senders[i]);
              elementToChange.className = "list-group-item message";
            }        
        }
      }
  }

</script>

<ul class="list-group" >
    <% users= [] %>
  <% signed_in_user.messages.each do |message| %>
 
    <%if !users.include?(message.sender) && message.sender != current_user.user_name%>
        <% users.push(message.sender) %>
        <li id = "<%= message.sender %>" class="list-group-item"> <%= link_to message.sender, messages_path() + "/" + message.sender %></li>
    <%end%>

  <%end%>
  <%= javascript_tag do %>
    var users= <%= users.to_json.html_safe%>
    var messages = <%= signed_in_user.messages.to_json.html_safe %>
     setMessageThumbnailNotification(users,messages);
  <%end %>
 

</ul>