config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/home', status: 302)
  get 'home', to: 'g_rabit#home', as: 'home'
  get 'messages', to: 'messages#messages', as: 'messages'
  get 'messages/:id', to: 'messages#message_board', as: 'message_board'
  post 'messages/:id', to: 'messages#send_message'
  devise_for :users
  get 'user_profile',to: 'g_rabit#user_profile', as: 'user_profile'
  get 'users', to: 'g_rabit#index', as: 'users' #list all users
  get 'users/:id',to:'g_rabit#deactivate', as:'deactivate' #Deactivated

  

  #routes for item model
  get 'items', to:'items#index', as:'items' #index
  get 'items/new', to: 'items#new', as: 'new_item' # new
  post 'items', to: 'items#create' # create
  get 'items/:id/edit', to: 'items#edit', as: 'edit_item' # edit
  patch 'items/:id', to: 'items#update' # update (as needed)
  put 'items/:id', to: 'items#update' # update (full replacement)
  get 'items/:id', to:'items#show', as:'item' #show
  delete 'items/:id', to: 'items#destroy' # destroy
  post 'items/:id',to:'items#reported' #reported

  get 'items/search_results/:id', to: 'items#search', as: 'search'
  get 'items/category_results/:id', to: 'items#search_by_category', as: 'category'

  #routes for Admin
  get 'administrator', to:'administrator#index', as:'admin' #index
  get 'reports', to:'administrator#view', as:'reports' #view
  get 'deactivated_users', to: 'administrator#userindex', as: 'deactivated_users' #list all deactivated users
  get 'deactivated_users/:id', to: 'administrator#reactivate', as: 'reactivate_users' #reactivate users
  get 'administrator/:id', to:'administrator#show', as:'admin_item' #show
  delete 'administrator/:id', to: 'administrator#destroy' # destroy
  
end

app/controllers/g_rabit_controller.rb
class GRabitController < ApplicationController
  
  def home
    respond_to do|format|
      format.html{render:home}
  end

  def user_profile
    respond_to do|format|
      format.html do
        if(user_signed_in?)
          render :user_profile
      
        else
          flash[:error] = "You must be signed in to access your user profile."
          redirect_to "/users/sign_in"
        end
      end
    end
  end
  
  def index
    @users = User.where.not(:id=>current_user.id)
    respond_to do|format|
      format.html {render:index, locals: {@users=>@users}}
    end
  end

    def deactivate
      user= User.find(params[:id])
      user.update_column(:is_deactivated,true)
      respond_to do |format|
          format.html do
              flash[:success] = 'User Deactivated '
              redirect_to users_url
          end
      end
    end

  end
end

app/helpers/g_rabit_helper.rb
module GRabitHelper
end

app/views/g_rabit/home.html.erb
<br>
<h1 class="text-center" style="margin-top:5px; color:lightyellow"><b><i>Welcome to gRabit!</i></b></h1>

<script>
    function searchForItem(){
        var search = document.getElementById("search_text").value;

        location.replace("items/search_results/"+ search);

}

    function enterKeyPressed(e){
        if(e.keyCode == 13 )
        {
            var search = document.getElementById("search_text").value;

            location.replace("items/search_results/"+ search);
        }

}
</script>
<div style="margin-top:30px">
<%= image_tag "logo3.png", width: 300, height: 280, class: 'd-block mx-auto' %></b>
</div>

<div id="search" class="row">
  
    <input type="text" name="search_text" id="search_text" placeholder="You'll find it here.." onKeyPress = "enterKeyPressed(event)"/>
    <button onclick = "searchForItem()" onKeyPress= "searchForItem()"> 🔎 </button>

</div>

app/views/g_rabit/index.html.erb
<div style="margin-top:20px; margin-bottom:25px; background-color:lightgreen">
<center><i><h2 style="color:black"><b> Users </b></h2></i>
</center>
</div>

<% @users.each do |it|%>

        <div class="jumbotron text-center hoverable p-3">
        
            <div class="row">
            
                <div class="col-md-4 offset-md-1 mx-3 my-3">
            
                
                <div class="view overlay">
                    
                    <% if it.profile_image.attached?%>
                        <%= image_tag url_for(it.profile_image.variant(resize: '200x300'))%>
                        <% end %>
                        <a>
                        <div class="mask rgba-white-slight"></div>
                        </a>
                   
                </div>
            
                </div>
            
                <div class="col-md-7 text-md-left ml-3 ">
            
                              
                    <h4 class="h4 mb-3" style="color: darkblue"><b> <%=it.name%></b> </h4>
                                        
                    <h4 class="h4 mb-3" style="color: darkblue" ><b> Username: <%=it.user_name%></b> </h4>
                    <h4 class="h4 mb-3" style="color: darkblue" ><i> <%=it.email%> </i></h4>
                    
                    <% if it.is_buyer && !it.is_seller %>
                    <h4 class="h4 mb-4" style="color: darkblue" ><b> Buyer </b></h4>    
                    <% end %>

                    <% if it.is_seller && !it.is_buyer %>
                    <h4 class="h4 mb-4" style="color: darkblue" ><b> Seller </b></h4>
                    <% end %>

                    <% if it.is_seller && it.is_buyer %>
                    <h4 class="h4 mb-4" style="color: darkblue" ><b> Both </b> </h4>
                    <% end %>

                    <% if !it.is_seller && !it.is_buyer %>
                    <h4 class="h4 mb-4" style="color: darkblue" ><b> None</b></h4>
                    <% end %>
                    
                    <% if it.is_deactivated %>
                    <h4 class="h4 mb-3" style="color: darkblue" ><b> Status: Inactive </b></h4>

                    <%else%>
                    
                    <h4 class="h4 mb-3" style="color: darkblue" ><b> Status: Active </b></h4>
                    
                    <h5><b> <%= link_to ' DEACTIVATE USER ', deactivate_path(it), class:"btn btn-danger btn-lg " %></b> </h5> 
                   
                    <%end%>





                   
                                
                </div>
            
            </div>
        
        </div>
<% end %>

app/views/g_rabit/user_profile.html.erb
<% if current_user.is_admin %>
    <div style ="margin-top:10px">
    </div>

    <div style = "float:left; margin-top:50px; margin-right:50px; margin-bottom:10px">
         <% if current_user.profile_image.attached?%>
          <%= image_tag url_for(current_user.profile_image.variant(resize: '150x200'))%>
         <% end %><br>
         <br>
         <b style = "margin-left:15px"><%= link_to "Edit Your Profile", edit_user_registration_path, class:"btn btn-primary btn-mi" %></b>
    </div>
    
    <div style ="float:left; margin-left:40px; margin-top:100px">
          <div><h4 style="color: lightgrey"><i><b>Name : <%=current_user.name%></b></i></h4></div> 
          <div><h4 style="color: lightgrey"><i><b>Username : <%=current_user.user_name%></b></i></h4></div>      
    </div>
         
    <center>
    <div style = "margin:20px" class ="container-sm float-right" >
    <h5><b> <%= link_to 'LIST OF ITEMS', admin_path, class:" btn btn-info btn-lg btn-block" %> </b></h5> 
    <h5><b> <%= link_to ' VIEW REPORTS ', reports_path, class:"btn btn-info btn-lg btn-block " %> </b></h5> 
    <h5><b> <%= link_to ' VIEW USERS ', users_path, class:"btn btn-info btn-lg btn-block" %> </b></h5> 
    <h5><b> <%= link_to ' VIEW DEACTIVATED ACCOUNTS ', deactivated_users_path, class:"btn btn-info btn-lg btn-block" %><b> </h5> 
    
    </div>
    </center>
        
<% end %>

<% if current_user.is_buyer && !current_user.is_seller && !current_user.is_admin %>
       
    <div style = "float:left; margin-top:100px; margin-right:50px; margin-bottom:10px">
        <% if current_user.profile_image.attached?%>
        <%= image_tag url_for(current_user.profile_image.variant(resize: '150x200'))%>
        <%else%>
        <div class="bg-light w-50 h-100 p-3 ">
        <h3 style="color:black"> Add Profile Picture Here</h4>
        </div>
        <% end %>
        <br>
        <br>
        <b><%= link_to "Edit Your Profile", edit_user_registration_path, class:"btn btn-warning btn-lg" %></b>
    </div>

    <div style ="float:left; margin-left:20px; margin-top:120px">
        <div><h4 style="color: lightgrey"><b>Name : <%=current_user.name%></b></h4></div> 
        <div><h4 style="color: lightgrey"><b>Username :  <%=current_user.user_name%></b></h4></div>
        <div><h4 style="color: lightgrey"><b>Role:  Buyer </b> </h4></div>
    </div>  
   
        
<% end %>

<% if current_user.is_seller && !current_user.is_buyer && !current_user.is_admin %>
  
    <div style = "float:left; margin-top:100px; margin-right:50px; margin-bottom:10px">
        <% if current_user.profile_image.attached?%>
        <%= image_tag url_for(current_user.profile_image.variant(resize: '150x200'))%>
        <%else%>
        <div class="bg-light w-50 h-100 p-3 ">
        <h3 style="color:black"> Add Profile Picture Here</h4>
        </div>
        <% end %>
        <br>
        <br>
        <b><%= link_to "Edit Your Profile", edit_user_registration_path, class:"btn btn-warning btn-lg" %></b>
    </div>

    <div style ="margin-left:20px; margin-top:120px; float:left">
      <div><h4 style="color: lightgrey"><b>Name : <%=current_user.name%></b></h4></div> 
        <div><h4 style="color: lightgrey"><b>Username :  <%=current_user.user_name%></b></h4></div>
        <div><h4 style="color: lightgrey"><b>Role:  Seller </b> </h4></div>
    </div> 
    
<% end %>

<% if current_user.is_buyer && current_user.is_seller && !current_user.is_admin%>
   
    <div style = "float:left; margin-top:100px; margin-right:50px; margin-bottom:10px">
        <% if current_user.profile_image.attached?%>
        <%= image_tag url_for(current_user.profile_image.variant(resize: '150x200'))%>
        <%else%>
        <div class="bg-light w-50 h-100 p-3 ">
        <h3 style="color:black"> Add Profile Picture Here</h4>
        </div>
        <% end %>
        <br>
        <br>
    <b><%= link_to "Edit Your Profile", edit_user_registration_path, class:"btn btn-warning btn-lg" %></b>
    </div>
    <div style ="margin-left:20px; margin-top:120px; float:left">
    <div><h4 style="color: lightgrey"><b>Name : <%=current_user.name%></b></h4></div> 
      <div><h4 style="color: lightgrey"><b>Username :  <%=current_user.user_name%></b></h4></div>
      <div><h4 style="color: lightgrey"><b>Role:  Both</b> </h4></div>
  </div> 
        
<% end %>

<% if !current_user.is_buyer && !current_user.is_seller && !current_user.is_admin%>
   
    <div style = "float:left; margin-top:100px; margin-right:50px; margin-bottom:10px">
        <% if current_user.profile_image.attached?%>
        <%= image_tag url_for(current_user.profile_image.variant(resize: '150x200'))%>
        <%else%>
        <div class="bg-light w-50 h-100 p-3 ">
        <h3 style="color:black"> Add Profile Picture Here</h4>
        </div>
        <% end %>
        <br>
        <br>
    <b><%= link_to "Edit Your Profile", edit_user_registration_path, class:"btn btn-warning btn-lg" %></b>
    </div>
    <div style ="margin-left:20px; margin-top:120px; float:left">
    <div><h4 style="color: lightgrey"><b>Name : <%=current_user.name%></b></h4></div> 
      <div><h4 style="color: lightgrey"><b>Username :  <%=current_user.user_name%></b></h4></div>
      <div><h4 style="color: lightgrey"><b>Role:  None</b> </h4></div>
  </div> 
        
<% end %>





    