config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/home', status: 302)
  get 'home', to: 'g_rabit#home', as: 'home'
  get 'messages', to: 'messages#messages', as: 'messages'
  get 'messages/:id', to: 'messages#message_board', as: 'message_board'
  post 'messages/:id', to: 'messages#send_message'
  devise_for :users
  get 'user_profile',to: 'g_rabit#user_profile', as: 'user_profile'
  get 'users', to: 'g_rabit#index', as: 'users' #list all users
  get 'users/:id',to:'g_rabit#deactivate', as:'deactivate' #Deactivated

  

  #routes for item model
  get 'items', to:'items#index', as:'items' #index
  get 'items/new', to: 'items#new', as: 'new_item' # new
  post 'items', to: 'items#create' # create
  get 'items/:id/edit', to: 'items#edit', as: 'edit_item' # edit
  patch 'items/:id', to: 'items#update' # update (as needed)
  put 'items/:id', to: 'items#update' # update (full replacement)
  get 'items/:id', to:'items#show', as:'item' #show
  delete 'items/:id', to: 'items#destroy' # destroy
  post 'items/:id',to:'items#reported' #reported

  get 'items/search_results/:id', to: 'items#search', as: 'search'
  get 'items/category_results/:id', to: 'items#search_by_category', as: 'category'

  #routes for Admin
  get 'administrator', to:'administrator#index', as:'admin' #index
  get 'reports', to:'administrator#view', as:'reports' #view
  get 'deactivated_users', to: 'administrator#userindex', as: 'deactivated_users' #list all deactivated users
  get 'deactivated_users/:id', to: 'administrator#reactivate', as: 'reactivate_users' #reactivate users
  get 'administrator/:id', to:'administrator#show', as:'admin_item' #show
  delete 'administrator/:id', to: 'administrator#destroy' # destroy
  
end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController
    before_action :authenticate_user!
    before_action :is_admin?, only: [:index]
    
    before_action :require_permission, only: [:destroy]

        
    def index
        itemlist = Item.all
        respond_to do |format|
            format.html { render:index, locals: { itemlist:itemlist} }
        end
    end

    def show
        item = nil
        if(params[:id] != "search_results")
            item = Item.find(params[:id])
        end

        respond_to do |format|
            format.html do 
                if(params[:id] == "search_results")
                    flash[:error] = "You must enter a value to search."
                    redirect_back(fallback_location: root_path)
                else
                 render:show, locals: { item:item} 
                end
            end
        end
    end

    def destroy
        item = Item.find(params[:id])
        item.destroy
        respond_to do |format|
            format.html do
                flash[:success] = 'Item removed successfully'
                redirect_to admin_url
            end
        end
    end
    
    def reactivate
        user= User.find(params[:id])
        user.update_column(:is_deactivated,false)
        respond_to do |format|
            format.html do
                flash[:success] = 'User Reactivated '
                redirect_to users_url
            end
        end
      end

    def userindex
        @users = User.where.not(:id=>current_user.id,:is_deactivated=>false)
        respond_to do|format|
         format.html {render:userindex, locals: {@users=>@users}}
         end
    end

    def view
        @items = Item.where("is_reported = ?",true)
        respond_to do |format|
            format.html { render:view, locals: { @items =>@items} }
        end
    end

    def require_permission
    
        if !current_user.is_admin
          redirect_to items_path, flash: { error: "You do not have permission to do that." }
        end
    end

    
    def is_admin?
        if(!current_user.is_admin)
            redirect_to :home, flash: { error: "You must be an administrator to view all items." }
        end
    end

end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/views/administrator/index.html.erb
<div style="margin:5px"> 
</div><br><br>
<% itemlist.each do |it|%>


        <div  style="background-color: lightgrey" class="jumbotron text-center hoverable p-4 ">
        
            <div class="row">
            
                <div class="col-md-4 offset-md-1 mx-3 my-3">
            
                <div class="view overlay">
                    <% if it.file.attached?%>
                        <% if it.file.image?%>
                        <%= image_tag url_for(it.file.variant(resize: '300x400'))%>
                        <% else %>
                        <%= video_tag url_for(it.file), style:'width:100%; height:auto', controls: ''%>
                        <% end %>
                        <a>
                        <div class="mask rgba-white-slight"></div>
                        </a>
                    <% end %>
                </div>
                
                </div>
            
                <div class="col-md-7 text-md-left ml-3 mt-3">
            
                <h4 class="h4 mb-3"><b> <%=it.name%> </b> </h4> 

                <h5 class="mb-3"><b><i> <%=it.category%> </i></b></h5>
                             
                
                <h5 class=" mb-3"><b><i> <%=it.description%> </i></b></h5>
                <h5 class=" mb-3"><b><i> Price: <%=it.price%></i></b></h5>
                
                 <h5 class=" mb-3"><b><i> Posted On: <%=it.created_at.strftime("%m/%d/%Y")%></i></b></h5>
                    
                    
                    <%= link_to 'View Item', admin_item_path(it), class:"btn btn-primary" %>
                    <%= link_to 'Delete Item', admin_item_path(it), method: :delete, class:"btn btn-danger" %>
                              
            
                </div>
            
            </div>
        
        </div>
<% end %>

app/views/administrator/show.html.erb
</br></br>
<div class="jumbotron hoverable p-5" >

  <div class="row" >

    <div class="col-md-4 offset-md-1 mx-3 my-3">

      <div class="view overlay">
            <% if item.file.attached?%>
                <% if item.file.image?%>
                <%= image_tag url_for(item.file.variant(resize: '300x400'))%>
                <% else %>
                <%= video_tag url_for(item.file), style:'width:100%; height:auto', controls: ''%>
                <% end %>
              <a>
                <div class="mask rgba-white-slight"></div>
              </a>
            <% end %>
      </div>
  </div>

  <div class="card-body">
      <h5 class="card-title"> <%=item.name%> </h5>
      <p class="card-text"> <%=item.description%> </p>
      <p class="card-text"> <%=item.price%> </p>
      <p class="card-text"> <%=item.category%> </p>
      <p class="card-text"> <%=item.creator.name%> </p>
       <p class="card-text"> <%=item.created_at.strftime("%m/%d/%Y")%> </p>
      

      <%= link_to 'Delete Item', admin_item_path(item),method: :delete, class:"btn btn-lg btn-danger" %>
      <%= link_to 'Go back', admin_path, class:"btn btn-lg btn-primary" %>
      <% user = User.find_by_id(item.user_id) %>
      
    </div>
</div>

app/views/administrator/userindex.html.erb
<div style="margin-top:20px; margin-bottom:25px; background-color:lightgreen">
<center>
<i><h2 style="color:black"><b> Deactivated Users </b></h2></i>
</center>
</div>



<% @users.each do |it|%>

        <div class="jumbotron text-center hoverable p-4">
        
            <div class="row">
            
                <div class="col-md-4 offset-md-1 mx-3 my-3">
            
                
                <div class="view overlay">
                    
                    <% if it.profile_image.attached?%>
                        <%= image_tag url_for(it.profile_image.variant(resize: '200x300'))%>
                        <% end %>
                        <a>
                        <div class="mask rgba-white-slight"></div>
                        </a>
                   
                </div>
            
                </div>
            
                <div class="col-md-7 text-md-left ml-3 ">
            
                              
                    <h4 class="h4 mb-3" style="color: darkblue"><b> <%=it.name%></b> </h4>
                                        
                    <h4 class="h4 mb-3" style="color: darkblue" ><b> Username: <%=it.user_name%></b> </h4>
                    <h4 class="h4 mb-3" style="color: darkblue" ><i> <%=it.email%> </i></h4>
                    
                    <% if it.is_buyer && !it.is_seller %>
                    <h4 class="h4 mb-4" style="color: darkblue" ><b> Buyer </b></h4>    
                    <% end %>

                    <% if it.is_seller && !it.is_buyer %>
                    <h4 class="h4 mb-4" style="color: darkblue" ><b> Seller </b></h4>
                    <% end %>

                    <% if it.is_seller && it.is_buyer %>
                    <h4 class="h4 mb-4" style="color: darkblue" ><b> Both </b> </h4>
                    <% end %>

                    <% if !it.is_seller && !it.is_buyer %>
                    <h4 class="h4 mb-4" style="color: darkblue" ><b> None</b></h4>
                    <% end %>
                    
                    <h4 class="h4 mb-3" style="color: darkblue" ><b> Status: Inactive </b></h4>

                    <h5><b> <%= link_to ' REACTIVATE USER ', reactivate_users_path(it), class:"btn btn-success btn-lg " %></b> </h5> 
                   
                                     
                                
                </div>
            
            </div>
        
        </div>
<% end %>

app/views/administrator/view.html.erb
<div style="margin:15px"> 
</div><br><br>

<% @items.each do |it|%>


        <div class="jumbotron text-center hoverable p-4">
        
            <div class="row">
            
                <div class="col-md-4 offset-md-1 mx-3 my-3">
            
                
                    <div class="view overlay">
                        <% if it.file.attached?%>
                            <% if it.file.image?%>
                            <%= image_tag url_for(it.file.variant(resize: '300x400'))%>
                            <% else %>
                            <%= video_tag url_for(it.file), style:'width:100%; height:auto', controls: ''%>
                            <% end %>
                        <a>
                            <div class="mask rgba-white-slight"></div>
                        </a>
                        <% end %>
                    </div>
                
                </div>
            
                <div class="col-md-7 text-md-left ml-3 mt-3">
            
                              
                    <h6 class="h6 pb-1"><i class="fas fa-desktop pr-1"></i> <%=it.category%> </h6>
                
            
                    <h4 class="h4 mb-4"> <%=it.name%> </h4>
                
                    <p class="font-weight-normal"> Description: <%=it.description%> </p>
                    <p class="font-weight-normal"><strong> Price: <%=it.price%> </strong></p>
                    <p class="font-weight-normal"><strong> Posted On: <%=it.created_at.strftime("%m/%d/%Y")%> </strong></p>
                   
                    
                    
                    <%= link_to 'View', admin_item_path(it), class:"btn btn-primary" %>
                    <%= link_to 'Delete', admin_item_path(it), method: :delete, class:"btn btn-danger" %>
                   
                                
                </div>
            
            </div>
        
        </div>
<% end %>