config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/home', status: 302)
  get 'home', to: 'g_rabit#home', as: 'home'
  get 'messages', to: 'messages#messages', as: 'messages'
  get 'messages/:id', to: 'messages#message_board', as: 'message_board'
  post 'messages/:id', to: 'messages#send_message'
  devise_for :users
  get 'user_profile',to: 'g_rabit#user_profile', as: 'user_profile'
  get 'users', to: 'g_rabit#index', as: 'users' #list all users
  get 'users/:id',to:'g_rabit#deactivate', as:'deactivate' #Deactivated

  

  #routes for item model
  get 'items', to:'items#index', as:'items' #index
  get 'items/new', to: 'items#new', as: 'new_item' # new
  post 'items', to: 'items#create' # create
  get 'items/:id/edit', to: 'items#edit', as: 'edit_item' # edit
  patch 'items/:id', to: 'items#update' # update (as needed)
  put 'items/:id', to: 'items#update' # update (full replacement)
  get 'items/:id', to:'items#show', as:'item' #show
  delete 'items/:id', to: 'items#destroy' # destroy
  post 'items/:id',to:'items#reported' #reported

  get 'items/search_results/:id', to: 'items#search', as: 'search'
  get 'items/category_results/:id', to: 'items#search_by_category', as: 'category'

  #routes for Admin
  get 'administrator', to:'administrator#index', as:'admin' #index
  get 'reports', to:'administrator#view', as:'reports' #view
  get 'deactivated_users', to: 'administrator#userindex', as: 'deactivated_users' #list all deactivated users
  get 'deactivated_users/:id', to: 'administrator#reactivate', as: 'reactivate_users' #reactivate users
  get 'administrator/:id', to:'administrator#show', as:'admin_item' #show
  delete 'administrator/:id', to: 'administrator#destroy' # destroy
  
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :bigint           not null, primary key
#  category    :string
#  description :string
#  is_reported :boolean
#  is_viewable :boolean
#  name        :string
#  price       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#
# Indexes
#
#  index_items_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Item < ApplicationRecord
  @@categories = nil 

  has_one_attached :file


    belongs_to(
        :creator,
        class_name: 'User',
        foreign_key: 'user_id',
        inverse_of: :items
      )

      def self.categories
        @@categories = ["Antiques", "Art", "Baby", "Books", "Business & Industrial", "Clothing", "Money", "Collectibles", "Electronics" , "Crafts", "Toys", "Motors", "Memorabilia", "Health and Beauty", "Home", "Jewlry", "Music" , "Instruments", "Real Estate", "Services", "Sports", "Guns", "Event Tickets", "Gaming", "Miscellaneous"] 
        @@categories
      end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :authenticate_user!
    before_action :is_seller?, only: [:index]
    
    before_action :require_permission, only: [ :edit, :update, :destroy]


    def index
        items = current_user.items
        respond_to do |format|
            format.html { render:index, locals: { items:items} }
        end
    end

    def new
        item = Item.new
        respond_to do |format|
            format.html {  render:new, locals: {item:item}}
        end
    end

    def create
       
        item = current_user.items.build(params.require(:item).permit(:name, :description, :category, :price, :is_viewable,  :file))
        respond_to do |format|
            format.html do
            
                if item.save
                    flash[:success] = "Item saved successfully"
                    redirect_to items_url
                else
                    flash.now[:error] = "Error: Item could not be saved"
                    render :new, locals: { item: item }
                end
            end
        end

    end

    def edit
        item = Item.find(params[:id])
        respond_to do |format|
            format.html { render :edit, locals: { item: item } }
        end
    end

    def update
        item = Item.find(params[:id])
        respond_to do |format|
            format.html do

                if item.update(params.require(:item).permit(:name, :description, :category, :price, :is_viewable, :file))

                    flash[:success] = 'Item updated successfully'
                    redirect_to items_url
                else
                    # error message
                    flash.now[:error] = 'Error: Item could not be updated'
                    # render edit
                    render :edit, locals: { item: item }
                end
            end
        end
    end


    def show
        item = nil
        
        if(params[:id] != "search_results")
            item = Item.find(params[:id])
        end

        respond_to do |format|
            format.html do 
                if(params[:id] == "search_results")
                    flash[:error] = "You must enter a value to search."
                    redirect_back(fallback_location: root_path)
                else
                 render:show, locals: { item:item} 
                end
            end
        end
    end

    

    def destroy
        item = Item.find(params[:id])
        item.destroy
        respond_to do |format|
            format.html do
                flash[:success] = 'Item removed successfully'
                redirect_to items_url
            end
        end
    end


    def reported
        item=Item.find(params[:id])
        item.update_column(:is_reported,true)
        respond_to do |format|
            format.html do
                flash[:success] = 'Item reported to Admin '
                redirect_to :home
            end
        end
    end
    
    def require_permission
    
        if Item.find(params[:id]).creator != current_user
          redirect_to items_path, flash: { error: "You do not have permission to do that." }
        end
    end

    
    def is_seller?
        if(!current_user.is_seller)
            redirect_to :home, flash: { error: "You must be a seller to list items." }
        
        end
    end

    def search()
        respond_to do |format|
            query = params[:id]
            items = Item.where("(is_viewable = true and created_at > ?) and lower(name) like ? or lower(description) like ?", 30.days.ago, "%#{params[:id]}%".downcase,  "%#{params[:id]}%".downcase).to_a
            
            format.html do
                if(!items.empty?)
                    render :search_results, locals: {items: items, query: query}
                else
                    flash[:error] = "There were no results found for "+ params[:id]
                    redirect_to :home
                end
            end
        end

    end

    def search_by_category()

        respond_to do |format|
            query = params[:id]
            items = Item.where("is_viewable = true and lower(category) like ? and created_at > ? ", "%#{params[:id]}%".downcase,30.days.ago).to_a
            
            format.html do
                if(!items.empty?)
                    render :search_results, locals: {items: items, query: query}
                else
                    flash[:error] = "There were no results found for "+ params[:id]
                    redirect_to :home
                end
            end
        end

    end
end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/items/category_results.html.erb
<center><h2 class = "bg-success">Results for <%= query %></h2></center>

<% items.each do |it|%>


    <div class="jumbotron text-center hoverable p-4">
    
      <div class="row">
    
        <div class="col-md-4 offset-md-1 mx-3 my-3">
    
        
          <div class="view overlay">
          <% if it.file.attached?%>
          <% if it.file.image?%>
          <%= image_tag url_for(it.file.variant(resize: '300x400'))%>
          <% else %>
           <%= video_tag url_for(it.file), style:'width:100%; height:auto', controls: ''%>
           <% end %>
   <% end %>
            <a>
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>
    
        </div>
       
        <div class="col-md-7 text-md-left ml-3 mt-3">
    
         
          
            <h6 class="h6 pb-1"><i class="fas fa-desktop pr-1"></i> <%=it.category%> </h6>
          
    
          <h4 class="h4 mb-4"> <%=it.name%> </h4>
    
          <p class="font-weight-normal"> Description: <%=it.description%> </p>
          <p class="font-weight-normal"><strong> Price: <%=it.price%> </strong></p>
    
         
          <%= link_to 'View', item_path(it), class:"btn btn-primary" %>
          <% user = User.find_by_id(it.user_id) %>
          <%= link_to 'Message Seller', message_board_path(user.user_name),method: :get, class:"btn btn-warning" %>  
  
         
    
        </div>
    
      </div>
    
    </div>
    <% end %>

app/views/items/edit.html.erb
<div style="background-color:lightgreen; margin-top:15px; margin-bottom:25px">
<center><i><h2 style="color:white"><b>Edit Item </b></h2></i>
</center>
</div>

<%= form_with model: item, url: item_path, method: :patch, local: true, scope: :item do |f| %>
<div class ="form-group">
    <%= f.label :item_name, "Item Name:",class: "col-md-4 control-label", style: "color:white;" %><br>
    <%= f.text_field :name,class: "form-control" %>
</div>

<div class ="form-group">
    <%= f.label :item_description, "Item Description:",class: "col-md-4 control-label", style: "color:white;" %><br>
    <%= f.text_field :description,class: "form-control" %>
</div>

<div class ="form-group" style="color:white">

    <%= f.label "Select a Category:", class: "col-md-4 control-label", style: "color:white;" %> <br>

    <%= f.select :category, options_for_select(Item.categories), class: "col-md-4 control-label", style: "color:white;" %>
</div>


<div class ="form-group">
    <%= f.label :item_price, "Item Price:",class: "col-md-4 control-label", style: "color:white;" %><br>
    <%= f.text_field :price,class: "form-control" %>
</div>

<div class= "form-group" >
<%= f.label:item_image, "Upload Image/Video:", class:"col-md-4 control-label", style: "color:white;"%>

<%= f.file_field :file, class:"form-control", direct_upload: true%>
</div>
 

<div class = "form-group" style="margin-top:5px; margin-bottom:5px">
    <%= f.check_box :is_viewable %>  <label style="color:white">Viewable to buyers</label>
</div>

<%= f.submit "Update Item", class:"btn btn-primary" %>


<% end %>

app/views/items/index.html.erb
<br>
<%= link_to 'Add New Item', new_item_path, class:"btn btn-success but", style:"margin-top:10px" %><br><br>
<div class="container mydiv" >

    <div class="row" >
	<% items.each do |it|%>
        <div class="col-md-4" style="margin-bottom:15px">
            <!-- bbb_deals -->
            <div class="bbb_deals" style="height:100%">
                <div class="bbb_deals_slider_container">
                    <div class=" bbb_deals_item">
                        <div class="bbb_deals_image" style="height:200px">
                        <% if it.file.attached?%>
                            <% if it.file.image?%>
                                <%= image_tag url_for(it.file.variant(resize: '300x400'))%>
                            <% else %>
                                 <%= video_tag url_for(it.file), style:'width:100%; height:auto', controls: ''%>
                            <% end %>
                        <% else %>
                        <img src="/assets/insert.jpg" style="height:200px" />
                        <%end%>
                        </div>
                        <div class="bbb_deals_content">
                            <div class="bbb_deals_info_line d-flex flex-row justify-content-start">
                                <div class="bbb_deals_item_category">  <%= it.category%> </div>
                            </div>
                            <div class="bbb_deals_info_line d-flex flex-row justify-content-start">
                                <div class="bbb_deals_item_name"> <%= it.name%> </div>
                                <div class="bbb_deals_item_price ml-auto">  <%= it.price%> </div>
                            </div>
                            <div class="available">
                                <div class="available_line d-flex flex-row justify-content-start">
                                   <div class="available_title">Posted on: <span><%=it.created_at.strftime("%m/%d/%Y")%></span></div>
                                </div>
                                <div class="available_bar"><span style="width:17%"></span></div><br>
                                <% if it.creator == current_user %>
                                    <%= link_to 'View', item_path(it), class:"btn btn-primary" %>
                                    <%= link_to 'Edit', edit_item_path(it), class:"btn btn-primary" %>
                                    <%= link_to 'Delete', item_path(it), method: :delete, data: {confirm: "Are you sure?"},  class:"btn btn-danger" %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
		<% end %>
	</div>
</div>

app/views/items/new.html.erb
<div style="margin-top:20px; margin-bottom:20px; background-color:lightgreen">
<center>
<i><h2 style="color:white"><b>Add New Item  </b></h2></i>
</center>
</div>

<%= form_with model: item, url: items_path, method: :post, local: true, scope: :item do |f| %>

<div class ="form-group">
    <%= f.label :item_name, "Item Name:",class: "col-md-4 control-label", style: "color:white;" %><br>
    <%= f.text_field :name,class: "form-control" %>
</div>

<div class ="form-group">
    <%= f.label :item_description, "Item Description:",class: "col-md-4 control-label", style: "color:white;" %><br>
    <%= f.text_field :description,class: "form-control" %>
</div>


    


<div class ="form-group" style="color:white">


    <%= f.label "Select a Category:", class: "col-md-4 control-label" %><br> 
    <%= f.select :category, options_for_select(Item.categories), class: "col-md-4 control-label" %>
</div>


<div class ="form-group">
    <%= f.label :item_price, "Item Price:",class: "col-md-4 control-label", style: "color:white;" %><br>

    <%= f.text_field :price,class: "form-control" %>
</div>



<div class= "form-group" >
<%= f.label:item_image, "Upload Image/Video:", class:"col-md-4 control-label", style: "color:white;" %>
<%= f.file_field :file, class:"form-control", direct_upload: true%>

<div class = "form-group" style="margin-top:5px; margin-bottom:5px">
    <%= f.check_box :is_viewable %>  <label style="color:white">Viewable to buyers</label>

</div>

<%= f.submit "Add Item", class:"btn btn-primary" %>


<% end %>

app/views/items/search_results.html.erb
<div style=" margin-top:15px; margin-bottom:25px">
<center><i><h2 style="color:lightgreen"><b>Results for <%= query %></b></h2></i>
</center>
</div>

<% items.each do |it|%>


    <div class="jumbotron text-center hoverable p-4">
    
      <div class="row">
    
        <div class="col-md-4 offset-md-1 mx-3 my-3">
    
        
          <div class="view overlay">
          <% if it.file.attached?%>
          <% if it.file.image?%>
          <%= image_tag url_for(it.file.variant(resize: '300x400'))%>
          <% else %>
           <%= video_tag url_for(it.file), style:'width:100%; height:auto', controls: ''%>
           <% end %>
   <% end %>
            <a>
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>
    
        </div>
       
        <div class="col-md-7 text-md-left ml-3 mt-3">
    
         
          
            <h6 class="h6 pb-1"><i class="fas fa-desktop pr-1"></i> <%=it.category%> </h6>
          
    
          <h4 class="h4 mb-4"><strong> <%=it.name%></strong> </h4>
    
          <p class="font-weight-normal"> Description: <%=it.description%> </p>
          <p class="font-weight-normal"><strong> Price: <%=it.price%> </strong></p>
          <p class="font-weight-normal"><strong> Posted On: <%=it.created_at.strftime("%m/%d/%Y")%> </strong></p>
          
    
         
          <%= link_to 'View', item_path(it), class:"btn btn-primary" %>
          <% user = User.find_by_id(it.user_id) %>
          <% if current_user.user_name != user.user_name %>
           <%= link_to 'Message Seller', message_board_path(user.user_name),method: :get, class:"btn btn-warning" %>  
          <% end %>
         
    
        </div>
    
      </div>
    
    </div>
    <% end %>

app/views/items/show.html.erb
<div style="margin-top:25px">

</div>
<div class="container">
		<div class="card">
			<div class="container-fliud">
				<div class="wrapper row">
					<div class="preview col-md-6">
						
						<div class="preview-pic tab-content">
						  <div class="tab-pane active" id="pic-1">
              <% if item.file.attached?%>
                <% if item.file.image?%>
                  <%= image_tag url_for(item.file.variant(resize: '300x400'))%>
                <% else %>
                  <%= video_tag url_for(item.file), style:'width:100%; height:auto', controls: ''%>
                <% end %>
              <% end %>
              </div>
						</div>
						
					</div>
					<div class="details col-md-6">
						<h3 class="product-title"> <%=item.name%> </h3>
						<p class="product-description"> <%=item.description%> </p>
            <h4>Category: <span> <%=item.category%> </span></h4>
						<h4>Price: <span>  <%= item.price%> </span></h4>
						<h4>Posted on: <span><%=item.created_at.strftime("%m/%d/%Y")%></span>
						<br/>
						<br/>
						
						
						<div class="action">
							<% if item.creator == current_user %>
                  <%= link_to 'Edit', edit_item_path(item), class:"btn btn-primary" %>
                  <%= link_to 'Delete', item_path(item),method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger" %>
              <% end %>
              <% user = User.find_by_id(item.user_id) %>
              <% if current_user.user_name != user.user_name %>
                  <%= link_to 'Message Seller', message_board_path(user.user_name),method: :get, class:"btn btn-warning" %>  
              <% end %>
              <% if item.creator != current_user %> 
                  <%= link_to 'Report the Item', item_path(item),method: :post,class:"btn btn-info" %>
              <% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<br>
	<b><center><%= link_to "Back", user_profile_path, class:"btn btn-success btn-lg" %></b>
    </center>